#!/usr/bin/env ruby

require_relative '../lib/startling_trello'

exit 1 if ARGV.empty?

puts "Fetching lists..."

StartlingTrello::Configuration.load_configuration

api = StartlingTrello.api
board = api.find_board(ARGV[0])

puts "ID\tList Name"
board.lists.each { |b| puts "#{b.id}\t#{b.name}" }
