require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

module Bundler
  class GemHelper
    protected

    def version_tag
      "startling-#{version}"
    end
  end
end
